# Generated by Django 5.2.7 on 2025-10-28 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_passwordresetotp_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
